const fs = require('fs');
const path = require('path');

const newKeysBase = {
  // Disease Detect
  "detect.title": "Disease Detection (Vision AI)",
  "detect.subtitle": "Upload a crop leaf image to detect diseases using CNN-based vision analysis. Simulated MobileNet/ResNet model for demonstration.",
  "detect.uploadCard": "Upload Crop Image",
  "detect.cropType": "Crop Type",
  "detect.leafImage": "Leaf Image",
  "detect.imageUploaded": "Image uploaded. Click analyze to detect diseases.",
  "detect.clickToUpload": "Click or drag to upload a leaf image",
  "detect.supportedFormats": "JPG, PNG supported",
  "detect.btnAnalyze": "Analyze Image",
  "detect.btnAnalyzing": "Analyzing with Vision AI...",
  "detect.demoTip": "Demo Tip",
  "detect.demoDesc": "Upload any leaf photo to see the AI analysis. The simulation will generate realistic disease detection results based on your selected crop type.",
  "detect.resultTitle": "Detection Result",
  "detect.severity": "Severity",
  "detect.confidence": "Confidence:",
  "detect.treatment": "Recommended Treatment",
  "detect.preventive": "Preventive Measures",

  // Disease Risk
  "risk.title": "Disease Risk Forecasting",
  "risk.subtitle": "Predict disease probability for the next 7-10 days using weather data and crop type. Simulated LSTM/GRU time-series model.",
  "risk.inputCard": "Weather & Crop Data",
  "risk.tempLabel": "Temperature (°C)",
  "risk.humidityLabel": "Humidity (%)",
  "risk.rainfallLabel": "Rainfall (mm/day)",
  "risk.btnForecast": "Forecast Disease Risk",
  "risk.btnForecasting": "Forecasting...",
  "risk.riskCard": "Disease Risk (Next",
  "risk.daysSuffix": "Days)",
  "risk.safe": "Safe",
  "risk.critical": "Critical",
  "risk.topThreats": "Top Disease Threats",
  "risk.factors": "Contributing Factors",
  "risk.aiRec": "AI Recommendation",

  // Profit Predict
  "profit.title": "Yield & Profit Prediction",
  "profit.subtitle": "Estimate expected yield, market price, input costs, and profit per acre. Simulated Random Forest / XGBoost regression model.",
  "profit.farmDetails": "Farm Details",
  "profit.acreage": "Acreage",
  "profit.irrigation": "Irrigation Type",
  "profit.soil": "Soil Type",
  "profit.btnPredict": "Predict Profit",
  "profit.btnPredicting": "Predicting...",
  "profit.revAcre": "Revenue / Acre",
  "profit.costAcre": "Cost / Acre",
  "profit.profitAcre": "Profit / Acre",
  "profit.profitRange": "Profit Range:",
  "profit.to": "to",
  "profit.perAcre": "per acre",
  "profit.for": "For",
  "profit.acres": "acres:",
  "profit.totalEst": "total estimated profit",
  "profit.modelConf": "Model Confidence",
  "profit.expYield": "Expected Yield",
  "profit.marketPrice": "Market Price",
  "profit.range": "Range:",
  "profit.costBreakdown": "Input Cost Breakdown (Per Acre)",
  "profit.totalInput": "Total Input Cost",
  "profit.riskFactors": "Risk Factors",

  // Common irrigation / soil
  "irrigationType.Canal": "Canal",
  "irrigationType.Drip": "Drip",
  "irrigationType.Sprinkler": "Sprinkler",
  "irrigationType.Rain-fed": "Rain-fed",
  "soilType.Alluvial": "Alluvial",
  "soilType.Black": "Black",
  "soilType.Red": "Red",
  "soilType.Laterite": "Laterite"
};

const orTranslations = {
  "detect.title": "ରୋଗ ଚିହ୍ନଟ (ଭିଜନ୍ AI)",
  "detect.subtitle": "CNN ଆଧାରିତ ଭିଜନ୍ ବିଶ୍ଳେଷଣ ବ୍ୟବହାର କରି ରୋଗ ଚିହ୍ନଟ କରିବା ପାଇଁ ଏକ ଫସଲ ପତ୍ରର ଚିତ୍ର ଅପଲୋଡ୍ କରନ୍ତୁ।",
  "detect.uploadCard": "ଫସଲ ଚିତ୍ର ଅପଲୋଡ୍ କରନ୍ତୁ",
  "detect.cropType": "ଫସଲ ପ୍ରକାର",
  "detect.leafImage": "ପତ୍ର ଚିତ୍ର",
  "detect.imageUploaded": "ଚିତ୍ର ଅପଲୋଡ୍ ହୋଇଛି। ରୋଗ ଚିହ୍ନଟ କରିବାକୁ ବିଶ୍ଳେଷଣ ଉପରେ କ୍ଲିକ୍ କରନ୍ତୁ।",
  "detect.clickToUpload": "ଏକ ପତ୍ର ଚିତ୍ର ଅପଲୋଡ୍ କରିବାକୁ କ୍ଲିକ୍ କରନ୍ତୁ କିମ୍ବା ଟାଣନ୍ତୁ",
  "detect.supportedFormats": "JPG, PNG ସମର୍ଥିତ",
  "detect.btnAnalyze": "ଚିତ୍ର ବିଶ୍ଳେଷଣ କରନ୍ତୁ",
  "detect.btnAnalyzing": "ଭିଜନ୍ AI ସହିତ ବିଶ୍ଳେଷଣ କରୁଛି...",
  "detect.demoTip": "ଡେମୋ ଟିପ୍",
  "detect.demoDesc": "AI ବିଶ୍ଳେଷଣ ଦେଖିବାକୁ ଯେକୌଣସି ପତ୍ରର ଫଟୋ ଅପଲୋଡ୍ କରନ୍ତୁ।",
  "detect.resultTitle": "ଚିହ୍ନଟ ଫଳାଫଳ",
  "detect.severity": "ତୀବ୍ରତା",
  "detect.confidence": "ଆତ୍ମବିଶ୍ୱାସ:",
  "detect.treatment": "ସୁପାରିଶ କରାଯାଇଥିବା ଚିକିତ୍ସା",
  "detect.preventive": "ନିରାକରଣ ପଦକ୍ଷେପ",

  "risk.title": "ରୋଗ ବିପଦର ପୂର୍ବାନୁମାନ",
  "risk.subtitle": "ପାଣିପାଗ ତଥ୍ୟ ଏବଂ ଫସଲ ପ୍ରକାର ବ୍ୟବହାର କରି ଆଗାମୀ 7-10 ଦିନ ପାଇଁ ରୋଗର ସମ୍ଭାବନା ଆକଳନ କରନ୍ତୁ।",
  "risk.inputCard": "ପାଣିପାଗ ଏବଂ ଫସଲ ତଥ୍ୟ",
  "risk.tempLabel": "ତାପମାତ୍ରା (°C)",
  "risk.humidityLabel": "ଆର୍ଦ୍ରତା (%)",
  "risk.rainfallLabel": "ବୃଷ୍ଟିପାତ (mm/ଦିନ)",
  "risk.btnForecast": "ରୋଗ ବିପଦର ପୂର୍ବାନୁମାନ କରନ୍ତୁ",
  "risk.btnForecasting": "ପୂର୍ବାନୁମାନ କରୁଛି...",
  "risk.riskCard": "ରୋଗର ବିପଦ (ଆଗାମୀ",
  "risk.daysSuffix": "ଦିନ)",
  "risk.safe": "ନିରାପଦ",
  "risk.critical": "ଗୁରୁତର",
  "risk.topThreats": "ପ୍ରମୁଖ ରୋଗର ଆଶଙ୍କା",
  "risk.factors": "ପ୍ରଭାବିତ କରୁଥିବା କାରଣଗୁଡିକ",
  "risk.aiRec": "AI ସୁପାରିଶ",

  "profit.title": "ଅମଳ ଏବଂ ଲାଭର ପୂର୍ବାନୁମାନ",
  "profit.subtitle": "ଆଶା କରାଯାଉଥିବା ଅମଳ, ବଜାର ମୂଲ୍ୟ, ଖର୍ଚ୍ଚ ଏବଂ ଏକର ପିଛା ଲାଭର ଆକଳନ କରନ୍ତୁ।",
  "profit.farmDetails": "ଫାର୍ମ ବିବରଣୀ",
  "profit.acreage": "ଏକର",
  "profit.irrigation": "ଜଳସେଚନ ପ୍ରକାର",
  "profit.soil": "ମୃତ୍ତିକା ପ୍ରକାର",
  "profit.btnPredict": "ଲାଭର ଅନୁମାନ କରନ୍ତୁ",
  "profit.btnPredicting": "ଅନୁମାନ କରୁଛି...",
  "profit.revAcre": "ଏକର ପିଛା ରାଜସ୍ୱ",
  "profit.costAcre": "ଏକର ପିଛା ଖର୍ଚ୍ଚ",
  "profit.profitAcre": "ଏକର ପିଛା ଲାଭ",
  "profit.profitRange": "ଲାଭ ପରିସର:",
  "profit.to": "ରୁ",
  "profit.perAcre": "ଏକର ପିଛା",
  "profit.for": "",
  "profit.acres": "ଏକର ପାଇଁ:",
  "profit.totalEst": "ମୋଟ ଆକଳନ କରାଯାଇଥିବା ଲାଭ",
  "profit.modelConf": "ମଡେଲର ଆତ୍ମବିଶ୍ୱାସ",
  "profit.expYield": "ଆଶା କରାଯାଉଥିବା ଅମଳ",
  "profit.marketPrice": "ବଜାର ମୂଲ୍ୟ",
  "profit.range": "ପରିସର:",
  "profit.costBreakdown": "ଇନପୁଟ୍ ଖର୍ଚ୍ଚ ବିବରଣୀ (ଏକର ପିଛା)",
  "profit.totalInput": "ମୋଟ ଇନପୁଟ୍ ଖର୍ଚ୍ଚ",
  "profit.riskFactors": "ବିପଦ କାରଣଗୁଡିକ",

  "irrigationType.Canal": "କେନାଲ୍",
  "irrigationType.Drip": "ଡ୍ରିପ୍",
  "irrigationType.Sprinkler": "ସ୍ପ୍ରିଙ୍କଲର୍",
  "irrigationType.Rain-fed": "ବର୍ଷା ଆଧାରିତ",
  "soilType.Alluvial": "ପଟୁ",
  "soilType.Black": "କଳା ମାଟି",
  "soilType.Red": "ନାଲି ମାଟି",
  "soilType.Laterite": "ଲାଟେରାଇଟ୍"
};

const hiTranslations = {
  "detect.title": "रोग का पता लगाना (विज़न एआई)",
  "detect.subtitle": "सीएनएन-आधारित दृष्टि विश्लेषण का उपयोग करके बीमारियों का पता लगाने के लिए फसल के पत्ते की छवि अपलोड करें।",
  "detect.uploadCard": "फसल छवि अपलोड करें",
  "detect.cropType": "फसल का प्रकार",
  "detect.leafImage": "पत्ती की छवि",
  "detect.imageUploaded": "छवि अपलोड की गई। रोग का पता लगाने के लिए विश्लेषण पर क्लिक करें।",
  "detect.clickToUpload": "पत्ती की छवि अपलोड करने के लिए क्लिक करें या खींचें",
  "detect.supportedFormats": "JPG, PNG समर्थित",
  "detect.btnAnalyze": "छवि का विश्लेषण करें",
  "detect.btnAnalyzing": "विज़न एआई के साथ विश्लेषण हो रहा है...",
  "detect.demoTip": "डेमो टिप",
  "detect.demoDesc": "एआई विश्लेषण देखने के लिए किसी भी पत्ते की फोटो अपलोड करें।",
  "detect.resultTitle": "पहचान परिणाम",
  "detect.severity": "गंभीरता",
  "detect.confidence": "विश्वास:",
  "detect.treatment": "अनुशंसित उपचार",
  "detect.preventive": "निवारक उपाय",

  "risk.title": "रोग जोखिम का पूर्वानुमान",
  "risk.subtitle": "मौसम डेटा और फसल के प्रकार का उपयोग करके अगले 7-10 दिनों के लिए रोग की संभावना का अनुमान लगाएं।",
  "risk.inputCard": "मौसम और फसल डेटा",
  "risk.tempLabel": "तापमान (°C)",
  "risk.humidityLabel": "नमी (%)",
  "risk.rainfallLabel": "वर्षा (मिमी/दिन)",
  "risk.btnForecast": "रोग जोखिम का पूर्वानुमान लगाएं",
  "risk.btnForecasting": "पूर्वानुमान हो रहा है...",
  "risk.riskCard": "रोग का जोखिम (अगले",
  "risk.daysSuffix": "दिन)",
  "risk.safe": "सुरक्षित",
  "risk.critical": "गंभीर",
  "risk.topThreats": "शीर्ष रोग खतरे",
  "risk.factors": "योगदान देने वाले कारक",
  "risk.aiRec": "एआई सिफ़ारिश",

  "profit.title": "उपज और लाभ की भविष्यवाणी",
  "profit.subtitle": "अपेक्षित उपज, बाजार मूल्य, इनपुट लागत और प्रति एकड़ लाभ का अनुमान लगाएं।",
  "profit.farmDetails": "खेत का विवरण",
  "profit.acreage": "रकबा (एकड़)",
  "profit.irrigation": "सिंचाई का प्रकार",
  "profit.soil": "मिट्टी के प्रकार",
  "profit.btnPredict": "लाभ की भविष्यवाणी करें",
  "profit.btnPredicting": "भविष्यवाणी हो रही है...",
  "profit.revAcre": "राजस्व / एकड़",
  "profit.costAcre": "लागत / एकड़",
  "profit.profitAcre": "लाभ / एकड़",
  "profit.profitRange": "लाभ सीमा:",
  "profit.to": "से",
  "profit.perAcre": "प्रति एकड़",
  "profit.for": "",
  "profit.acres": "एकड़ के लिए:",
  "profit.totalEst": "कुल अनुमानित लाभ",
  "profit.modelConf": "मॉडल का विश्वास",
  "profit.expYield": "अपेक्षित उपज",
  "profit.marketPrice": "बाजार मूल्य",
  "profit.range": "सीमा:",
  "profit.costBreakdown": "इनपुट लागत विवरण (प्रति एकड़)",
  "profit.totalInput": "कुल इनपुट लागत",
  "profit.riskFactors": "जोखिम कारक",

  "irrigationType.Canal": "नहर",
  "irrigationType.Drip": "ड्रिप",
  "irrigationType.Sprinkler": "स्प्रिंकलर",
  "irrigationType.Rain-fed": "वर्षा सिंचित",
  "soilType.Alluvial": "जलोढ़",
  "soilType.Black": "काली मिट्टी",
  "soilType.Red": "लाल मिट्टी",
  "soilType.Laterite": "लेटराइट"
};

const langs = [
  { code: 'en', extra: newKeysBase },
  { code: 'hi', extra: hiTranslations },
  { code: 'or', extra: orTranslations }
];

langs.forEach(lang => {
  const p = path.join(__dirname, 'src', 'translations', `${lang.code}.json`);
  let data = {};
  if (fs.existsSync(p)) {
    data = JSON.parse(fs.readFileSync(p, 'utf8'));
  }
  data = { ...data, ...lang.extra };
  fs.writeFileSync(p, JSON.stringify(data, null, 2));
});
