const fs = require('fs');
const path = require('path');

const newKeysBase = {
  // Irrigation
  "irrig.title": "Smart Irrigation Advisor",
  "irrig.subtitle": "AI-powered soil moisture prediction, pump automation, and water optimization",
  "irrig.btnAnalyze": "Analyze Irrigation Need",
  "irrig.btnAnalyzing": "Analyzing...",
  "irrig.moisture": "Soil Moisture",
  "irrig.pumpStatus": "Pump Status",
  "irrig.waterSaved": "Water Saved",
  "irrig.vsFlood": "vs flood irrigation",
  "irrig.overRisk": "Over-irrigation Risk",
  "irrig.scoreOut": "Score out of 100",
  "irrig.decision": "Irrigation Decision",
  "irrig.waterReq": "Water Required",
  "irrig.costSaving": "Cost Saving",
  "irrig.pumpOverride": "Pump Manual Override (IoT Simulation)",
  "irrig.auto": "Auto",
  "irrig.forceOn": "Force ON",
  "irrig.forceOff": "Force OFF",
  "irrig.overrideActive": "Manual override active. AI recommendation paused.",
  "irrig.schedule": "7-Day Irrigation Schedule",

  // Pest
  "pest.title": "Pest & Disease Outbreak Forecasting",
  "pest.subtitle": "Regional outbreak risk prediction with district-level alerts. Predict before it spreads.",
  "pest.btnForecast": "Forecast Pest Outbreak",
  "pest.btnForecasting": "Forecasting...",
  "pest.prob": "Outbreak Probability",
  "pest.regClass": "Regional Classification",
  "pest.riskZone": "Risk Zone",
  "pest.cropsAtRisk": "Crops at Risk",
  "pest.distAlerts": "District-Level Alerts",
  "pest.prevAdvisory": "Preventive Advisory",

  // SMS Alerts
  "sms.title": "SMS Alert System",
  "sms.subtitle": "Event-driven alerts with gateway abstraction, retry logic, deduplication, and delivery monitoring.",
  "sms.tabTrigger": "Event Trigger",
  "sms.tabManual": "Manual SMS",
  "sms.tabHistory": "Alert History",
  "sms.tabMonitor": "Monitoring",
  "sms.farmerPhone": "Farmer Phone",
  "sms.btnTrigger": "Evaluate & Trigger Alerts",
  "sms.btnEvaluating": "Evaluating...",
  "sms.eventsEval": "Events Evaluated",
  "sms.alertsSent": "Alerts Sent",
  "sms.dupSkipped": "Duplicates Skipped",
  "sms.threshEval": "Threshold Evaluations",
  "sms.sentDetails": "Sent Alert Details",
  "sms.sendManual": "Send Manual SMS",
  "sms.phoneCountry": "Phone Number (with country code)",
  "sms.priority": "Priority",
  "sms.message": "Message",
  "sms.btnSend": "Send SMS",
  "sms.btnSending": "Sending...",
  "sms.valError": "Validation Errors:",
  "sms.btnLoadHistory": "Load Alert History",
  "sms.btnRetry": "Retry Failed",
  "sms.retried": "Retried",
  "sms.recovered": "Recovered",
  "sms.stillFailed": "Still Failed",
  "sms.totalSent": "Total Sent",
  "sms.delivered": "Delivered",
  "sms.failed": "Failed",
  "sms.retrying": "Retrying",
  "sms.successRate": "Success Rate",

  // Chatbot
  "chat.title": "AI Farm Assistant",
  "chat.subtitle": "Ask questions about diseases, profit, irrigation, market advice, and more in simple language.",
  "chat.context": "Context:",
  "chat.placeholder": "Ask about your crop, disease, profit, market...",
  "chat.thinking": "Thinking…",

  // Voice Assistant
  "voice.title": "KisanBot Voice Assistant",
  "voice.subtitle": "Speech-to-text → Claude crop advice → Spoken reply",
  "voice.autoSpeak": "Auto-speak",
  "voice.muted": "Muted",
  "voice.playAnswer": "Play answer",
  "voice.language": "Language",
  "voice.unsupported": "Voice features aren’t supported in this browser. Try Chrome/Edge on desktop or Android.",
  "voice.listening": "Listening…",
  "voice.tapMic": "Tap the mic to speak",
  "voice.heard": "Heard:",
};

// ... Odia ...
const orTranslations = {
  "irrig.title": "ସ୍ମାର୍ଟ ଜଳସେଚନ ପରାମର୍ଶଦାତା",
  "irrig.subtitle": "AI ଆଧାରିତ ମୃତ୍ତିକା ଆର୍ଦ୍ରତା ପୂର୍ବାନୁମାନ ଏବଂ ସ୍ୱୟଂଚାଳିତ ଜଳସେଚନ",
  "irrig.btnAnalyze": "ଜଳସେଚନ ଆବଶ୍ୟକତା ବିଶ୍ଳେଷଣ କରନ୍ତୁ",
  "irrig.btnAnalyzing": "ବିଶ୍ଳେଷଣ କରୁଛି...",
  "irrig.moisture": "ମୃତ୍ତିକା ଆର୍ଦ୍ରତା",
  "irrig.pumpStatus": "ପମ୍ପ ସ୍ଥିତି",
  "irrig.waterSaved": "ସଞ୍ଚିତ ଜଳ",
  "irrig.vsFlood": "ବନ୍ୟା ଜଳସେଚନ ତୁଳନାରେ",
  "irrig.overRisk": "ଅଧିକ ଜଳସେଚନ ବିପଦ",
  "irrig.scoreOut": "100 ରୁ ସ୍କୋର",
  "irrig.decision": "ଜଳସେଚନ ନିଷ୍ପତ୍ତି",
  "irrig.waterReq": "ଆବଶ୍ୟକ ଜଳ",
  "irrig.costSaving": "ମୂଲ୍ୟ ସଞ୍ଚୟ",
  "irrig.pumpOverride": "ପମ୍ପ ନିୟନ୍ତ୍ରଣ",
  "irrig.auto": "ସ୍ୱୟଂଚାଳିତ",
  "irrig.forceOn": "ଅନ୍ କରନ୍ତୁ",
  "irrig.forceOff": "ଅଫ୍ କରନ୍ତୁ",
  "irrig.overrideActive": "ମାନୁଆଲ ନିୟନ୍ତ୍ରଣ ସକ୍ରିୟ ଅଛି। AI ପରାମର୍ଶ ସ୍ଥଗିତ ରହିଛି।",
  "irrig.schedule": "7-ଦିନିଆ ଜଳସେଚନ କାର୍ଯ୍ୟସୂଚୀ",

  "pest.title": "ରୋଗ ଏବଂ କୀଟ ଆକ୍ରମଣର ପୂର୍ବାନୁମାନ",
  "pest.subtitle": "ଜିଲ୍ଲା ସ୍ତରୀୟ ସତର୍କ ସୂଚନା ସହିତ ଆଞ୍ଚଳିକ ବିପଦର ପୂର୍ବାନୁମାନ",
  "pest.btnForecast": "କୀଟ ଆକ୍ରମଣର ପୂର୍ବାନୁମାନ କରନ୍ତୁ",
  "pest.btnForecasting": "ପୂର୍ବାନୁମାନ କରୁଛି...",
  "pest.prob": "ଆକ୍ରମଣ ସମ୍ଭାବନା",
  "pest.regClass": "ଆଞ୍ଚଳିକ ବର୍ଗୀକରଣ",
  "pest.riskZone": "ବିପଦ ଜୋନ୍",
  "pest.cropsAtRisk": "ବିପଦରେ ଥିବା ଫସଲ",
  "pest.distAlerts": "ଜିଲ୍ଲା ସ୍ତରୀୟ ସତର୍କ ସୂଚନା",
  "pest.prevAdvisory": "ନିରାକରଣ ପରାମର୍ଶ",

  "sms.title": "SMS ସତର୍କତା ସିଷ୍ଟମ୍",
  "sms.subtitle": "ଇଭେଣ୍ଟ-ଆଧାରିତ ସତର୍କତା ସିଷ୍ଟମ୍",
  "sms.tabTrigger": "ଇଭେଣ୍ଟ ଟ୍ରିଗର",
  "sms.tabManual": "ମାନୁଆଲ SMS",
  "sms.tabHistory": "ଇତିହାସ",
  "sms.tabMonitor": "ମନିଟରିଂ",
  "sms.farmerPhone": "ଚାଷୀଙ୍କ ଫୋନ୍ ନମ୍ବର",
  "sms.btnTrigger": "ମୂଲ୍ୟାୟନ ଏବଂ ସତର୍କତା ପଠାନ୍ତୁ",
  "sms.btnEvaluating": "ମୂଲ୍ୟାୟନ କରୁଛି...",
  "sms.eventsEval": "ମୂଲ୍ୟାଙ୍କନ କରାଯାଇଥିବା ଘଟଣା",
  "sms.alertsSent": "ପଠାଯାଇଥିବା ସତର୍କତା",
  "sms.dupSkipped": "ନକଲି ବାଦ୍ ଦିଆଯାଇଛି",
  "sms.threshEval": "ସୀମା ମୂଲ୍ୟାୟନ",
  "sms.sentDetails": "ପଠାଯାଇଥିବା ବିବରଣୀ",
  "sms.sendManual": "ମାନୁଆଲ SMS ପଠାନ୍ତୁ",
  "sms.phoneCountry": "ଫୋନ୍ ନମ୍ବର (+ କୋଡ୍ ସହିତ)",
  "sms.priority": "ଅଗ୍ରାଧିକାର",
  "sms.message": "ବାର୍ତ୍ତା",
  "sms.btnSend": "SMS ପଠାନ୍ତୁ",
  "sms.btnSending": "ପଠାଉଛି...",
  "sms.valError": "ତ୍ରୁଟି:",
  "sms.btnLoadHistory": "ଇତିହାସ ଲୋଡ୍ କରନ୍ତୁ",
  "sms.btnRetry": "ପୁନର୍ବାର ଚେଷ୍ଟା କରନ୍ତୁ",
  "sms.retried": "ଚେଷ୍ଟା କରାଯାଇଛି",
  "sms.recovered": "ପୁନରୁଦ୍ଧାର ହୋଇଛି",
  "sms.stillFailed": "ବିଫଳ ହୋଇଛି",
  "sms.totalSent": "ମୋଟ ପଠାଯାଇଛି",
  "sms.delivered": "ବିତରଣ ହୋଇଛି",
  "sms.failed": "ବିଫଳ",
  "sms.retrying": "ଚେଷ୍ଟା କରୁଛି...",
  "sms.successRate": "ସଫଳତା ହାର",

  "chat.title": "AI ଫାର୍ମ ଆସିଷ୍ଟାଣ୍ଟ୍",
  "chat.subtitle": "ରୋଗ, ଲାଭ, ବଜାର ଏବଂ ଜଳସେଚନ ବିଷୟରେ ପଚାରନ୍ତୁ।",
  "chat.context": "ପ୍ରସଙ୍ଗ:",
  "chat.placeholder": "ଆପଣଙ୍କ ଫସଲ ବିଷୟରେ ପଚାରନ୍ତୁ...",
  "chat.thinking": "ଭାବୁଛି...",

  "voice.title": "କିସାନ୍ ବୋଟ୍ ଭଏସ୍ ଆସିଷ୍ଟାଣ୍ଟ୍",
  "voice.subtitle": "କଥା -> ବିଶ୍ଳେଷଣ -> ଉତ୍ତର",
  "voice.autoSpeak": "ସ୍ୱୟଂ କୁହନ୍ତୁ",
  "voice.muted": "ମ୍ୟୁଟ୍",
  "voice.playAnswer": "ଉତ୍ତର ଶୁଣନ୍ତୁ",
  "voice.language": "ଭାଷା",
  "voice.unsupported": "ଏହି ବ୍ରାଉଜର୍ ରେ ସମର୍ଥିତ ନୁହେଁ।",
  "voice.listening": "ଶୁଣୁଛି...",
  "voice.tapMic": "କହିବାକୁ ମାଇକ୍ ଉପରେ କ୍ଲିକ୍ କରନ୍ତୁ",
  "voice.heard": "ଶୁଣାଗଲା:",
};

// ... Hindi ...
const hiTranslations = {
  "irrig.title": "स्मार्ट सिंचाई सलाहकार",
  "irrig.subtitle": "एआई-संचालित मिट्टी की नमी की भविष्यवाणी और पंप स्वचालन",
  "irrig.btnAnalyze": "सिंचाई की आवश्यकता का विश्लेषण करें",
  "irrig.btnAnalyzing": "विश्लेषण हो रहा है...",
  "irrig.moisture": "मिट्टी की नमी",
  "irrig.pumpStatus": "पंप की स्थिति",
  "irrig.waterSaved": "पानी की बचत",
  "irrig.vsFlood": "बाढ़ सिंचाई बनाम",
  "irrig.overRisk": "अधिक सिंचाई का जोखिम",
  "irrig.scoreOut": "100 में से स्कोर",
  "irrig.decision": "सिंचाई का निर्णय",
  "irrig.waterReq": "आवश्यक पानी",
  "irrig.costSaving": "लागत की बचत",
  "irrig.pumpOverride": "पंप मैनुअल ओवरराइड",
  "irrig.auto": "ऑटो",
  "irrig.forceOn": "चालू करें",
  "irrig.forceOff": "बंद करें",
  "irrig.overrideActive": "मैनुअल ओवरराइड सक्रिय है। एआई सिफारिश रोक दी गई।",
  "irrig.schedule": "7-दिवसीय सिंचाई अनुसूची",

  "pest.title": "कीट व रोग प्रकोप भविष्यवाणी",
  "pest.subtitle": "जिला-स्तरीय अलर्ट के साथ क्षेत्रीय प्रकोप जोखिम की भविष्यवाणी।",
  "pest.btnForecast": "प्रकोप की भविष्यवाणी करें",
  "pest.btnForecasting": "भविष्यवाणी हो रही है...",
  "pest.prob": "प्रकोप की संभावना",
  "pest.regClass": "क्षेत्रीय वर्गीकरण",
  "pest.riskZone": "जोखिम क्षेत्र",
  "pest.cropsAtRisk": "खतरे में फसलें",
  "pest.distAlerts": "ज़िला-स्तरीय अलर्ट",
  "pest.prevAdvisory": "निवारक सलाह",

  "sms.title": "एसएमएस अलर्ट सिस्टम",
  "sms.subtitle": "इवेंट-संचालित अलर्ट सिस्टम",
  "sms.tabTrigger": "इवेंट ट्रिगर",
  "sms.tabManual": "मैनुअल एसएमएस",
  "sms.tabHistory": "अलर्ट इतिहास",
  "sms.tabMonitor": "निगरानी",
  "sms.farmerPhone": "किसान का फोन",
  "sms.btnTrigger": "मूल्यांकन करें और अलर्ट भेजें",
  "sms.btnEvaluating": "मूल्यांकन हो रहा है...",
  "sms.eventsEval": "मूल्यांकित घटनाएँ",
  "sms.alertsSent": "भेजे गए अलर्ट",
  "sms.dupSkipped": "डुप्लीकेट छोड़ दिए गए",
  "sms.threshEval": "सीमा मूल्यांक",
  "sms.sentDetails": "भेजे गए अलर्ट का विवरण",
  "sms.sendManual": "मैनुअल एसएमएस भेजें",
  "sms.phoneCountry": "फोन नंबर (+ कोड के साथ)",
  "sms.priority": "प्राथमिकता",
  "sms.message": "संदेश",
  "sms.btnSend": "एसएमएस भेजें",
  "sms.btnSending": "भेजा जा रहा है...",
  "sms.valError": "त्रुटियाँ:",
  "sms.btnLoadHistory": "इतिहास लोड करें",
  "sms.btnRetry": "फिर से प्रयास करें",
  "sms.retried": "पुनः प्रयास किया गया",
  "sms.recovered": "पुनर्प्राप्त",
  "sms.stillFailed": "अभी भी विफल है",
  "sms.totalSent": "कुल भेजा गया",
  "sms.delivered": "डिलीवर हो गया",
  "sms.failed": "विफल",
  "sms.retrying": "पुनः प्रयास हो रहा है...",
  "sms.successRate": "सफलता दर",

  "chat.title": "एआई फार्म असिस्टेंट",
  "chat.subtitle": "रोग, लाभ, सिंचाई और बाजार के बारे में पूछें।",
  "chat.context": "प्रसंग:",
  "chat.placeholder": "अपनी फसल, बीमारी, लाभ आदि के बारे में पूछें...",
  "chat.thinking": "सोच रहा है...",

  "voice.title": "किसान बॉट वॉयस असिस्टेंट",
  "voice.subtitle": "स्पीच से टेक्स्ट -> क्लॉड कृषि सलाह -> वॉयस",
  "voice.autoSpeak": "ऑटो-स्पोक",
  "voice.muted": "म्यूट",
  "voice.playAnswer": "उत्तर चलाएं",
  "voice.language": "भाषा",
  "voice.unsupported": "आपका ब्राउज़र वॉयस का समर्थन नहीं करता है।",
  "voice.listening": "सुन रहा है...",
  "voice.tapMic": "बोलने के लिए माइक पर टैप करें",
  "voice.heard": "सुना गया:",
};

const langs = [
  { code: 'en', extra: newKeysBase },
  { code: 'hi', extra: hiTranslations },
  { code: 'or', extra: orTranslations }
];

langs.forEach(lang => {
  const p = path.join(__dirname, 'src', 'translations', `${lang.code}.json`);
  let data = {};
  if (fs.existsSync(p)) {
    data = JSON.parse(fs.readFileSync(p, 'utf8'));
  }
  data = { ...data, ...lang.extra };
  fs.writeFileSync(p, JSON.stringify(data, null, 2));
});
